PROGRAMS = date_spinbox date_spinbox_cb numeric_simplespin simplespin_value string_simplespin

CFLAGS=
INCLUDES = -I/usr/Motif21/include -I/usr/X11R6/include
LIBS= -L/usr/Motif21/lib -L/usr/X11R6/lib -lXm -lXt -lSM -lICE -lX11

all: $(PROGRAMS)

.c: ; $(CC) $(CFLAGS) $(INCLUDES) $@.c $(LIBS) -o $@

clean::
	-rm -f $(PROGRAMS) *.o

