PROGRAMS = build_menu build_option choice_popup file_menu popups reset_sensitive simple_option simple_popup simple_pullright

CFLAGS=
INCLUDES = -I/usr/Motif21/include -I/usr/X11R6/include
LIBS= -L/usr/Motif21/lib -L/usr/X11R6/lib -lXm -lXt -lSM -lICE -lX11

all: $(PROGRAMS)

.c: ; $(CC) $(CFLAGS) $(INCLUDES) $@.c $(LIBS) -o $@

clean::
	-rm -f $(PROGRAMS) *.o

